CREATE TABLE IF NOT EXISTS operacoes_ativas(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_OP DATE, 
    REG_ANS VARCHAR(50),
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO VARCHAR(100),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
);
